hexops/mach-sysgpu

src/Air.zig
src/Ast.zig
src/AstGen.zig
src/Parser.zig
src/test.zig

more astgen

---

src/Air.zig
src/AstGen.zig
src/ErrorList.zig
src/print_air.zig
src/test.zig

const expressions

---

src/Air.zig
src/AstGen.zig
src/print_air.zig
src/test.zig

code readability

---

src/Air.zig
src/Ast.zig
src/AstGen.zig
src/Parser.zig
src/print_air.zig
src/test.zig

call expr and zero construction

---

src/Air.zig
src/Ast.zig
src/AstGen.zig
src/Parser.zig
src/print_air.zig
src/test.zig

simplify instructions and scalar types construction

---

README.md
build.zig
src/Air.zig
src/Ast.zig
src/AstGen.zig
src/CodeGen.zig
src/Parser.zig
src/Tokenizer.zig
src/codegen/spirv.zig
src/print_air.zig
src/test.zig

finish AstGen

---

.github/workflows/ci.yml
src/Parser.zig

Fixes compile errors in #14, superceeding it

Update Zig to 0.11.0-dev.3664+0f5aff344

---

.github/workflows/ci.yml
build.zig
build.zig.zon
src/shader/Air.zig
src/shader/Ast.zig
src/shader/AstGen.zig
src/shader/Parser.zig
src/shader/codegen/spirv.zig
src/shader/codegen/spirv/Section.zig
src/shader/print_air.zig
src/shader/test.zig
src/shader/test/triangle.wgsl

update to latest zig

---

build.zig
src/main.zig
src/vulkan.zig

Update interface and dynamically load vulkan-loader

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/shader/test.zig
src/shader/test/triangle.wgsl

improve spirv codegen

---

build.zig.zon
examples/basic_init/main.zig
src/main.zig
src/shader/Ast.zig
src/shader/AstGen.zig
src/shader/Parser.zig
src/shader/Token.zig
src/shader/codegen/spirv.zig
src/shader/codegen/spirv/Section.zig
src/shader/codegen/spirv/spec.zig
src/vulkan.zig
tools/gen_spirv_spec.zig

update to latest zig API

---

src/shader/Air.zig
src/shader/Ast.zig
src/shader/AstGen.zig
src/shader/Parser.zig
src/shader/codegen/spirv.zig
src/shader/test.zig
src/shader/test/triangle.wgsl

improvements

---

src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/shader/print_air.zig
src/shader/test.zig

{spirv, AstGen}: emit matrix

---

src/main.zig
src/shader/Air.zig
src/shader/Ast.zig
src/shader/AstGen.zig
src/shader/CodeGen.zig
src/shader/Parser.zig
src/shader/codegen/SpirV.zig
src/shader/test.zig
src/vulkan/Adapter.zig
src/vulkan/Device.zig

shader: multiple bug fixes

---

src/shader/Air.zig
src/shader/Ast.zig
src/shader/AstGen.zig
src/shader/CodeGen.zig
src/shader/Parser.zig
src/shader/codegen/SpirV.zig
src/shader/codegen/spirv/Section.zig
src/shader/test.zig

spirv: emit debug source info

---

src/shader/AstGen.zig
src/shader/codegen/SpirV.zig
src/shader/codegen/spirv/Section.zig

spirv: emit loops and loop controlers

---

build.zig
examples/triangle/main.zig
src/main.zig
src/metal.zig
src/metal/conv.zig
src/metal/device.zig
src/metal/instance.zig
src/metal/objc/c.zig
src/metal/objc/ca.zig
src/metal/objc/mtl.zig
src/metal/objc/ns.zig
src/shader/CodeGen.zig
src/shader/codegen/msl.zig

Initial Metal backend

---

src/metal/device.zig
src/shader/codegen/msl.zig

metal: fix memory issues

---

src/metal/conv.zig
src/metal/device.zig

metal: render pipeline and render pass functionality

---

build.zig.zon
src/main.zig
src/metal.zig
src/metal/conv.zig
src/metal/device.zig

metal: texture, texture view, and msaa support

---

examples/triangle/shader.wgsl
src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/SpirV.zig
src/vulkan.zig

Closes https://github.com/hexops/mach/issues/1007

automatically cast AbstractInt into AbstractFloat

---

.github/workflows/ci.yml
examples/triangle/main.zig
src/shader/AstGen.zig

ci: run on all platforms

---

build.zig
build.zig.zon
src/d3d12.zig
src/d3d12/c.zig
src/d3d12/conv.zig
src/d3d12/notes.md
src/d3d12/workarounds.c
src/main.zig
src/shader/CodeGen.zig
src/shader/codegen/hlsl.zig

d3d12: initial backend

---

examples/triangle/main.zig
src/d3d12.zig
src/main.zig
src/metal.zig
src/vulkan.zig

all: add device lost callback

---

build.zig
build.zig.zon

build: escape transitive dependency hell

---

src/shader/AstGen.zig
src/shader/test.zig

AstGen: fix failing tests

---

build.zig
src/d3d12.zig
src/main.zig
src/vulkan.zig

all: test backends

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/vulkan.zig

metal: extract workgroup size from air

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/CodeGen.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig
src/shader/print_air.zig

{AstGen,spirv}: negate instruction

---

src/conventions.md
src/metal.zig
src/metal/conv.zig

metal: cleanup

---

build.zig

all: fix module dependencies

---

build.zig.zon
src/conventions.md
src/d3d12.zig
src/main.zig
src/metal.zig
src/metal/conv.zig
src/vulkan.zig

metal: map-async backend support

---

src/metal.zig
src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig

metal: rotating-cube and msl improvements

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig

AstGen: simplify unary and binary instructions

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig

metal: intrinsic functions

---

src/metal.zig
src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig

metal: boids example

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/vulkan.zig

metal: object recycling

---

src/metal.zig

metal: allocator optimizations

---

build.zig.zon
src/metal.zig

metal: swapchain options

---

build.zig.zon
src/metal.zig

metal: internal autorelease

---

src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/vulkan.zig
src/vulkan/proc.zig

spirv: make procedural-primitives's shader working

---

build.zig

build: fix lib c sources

---

src/d3d12.zig
src/vulkan.zig

{d3d12,vk}: fix setIndexBuffer return type

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig

shader: implement more builtins

---

src/shader/AstGen.zig
src/shader/test.zig

AstGen: fix recursive global variable references

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/shader/AstGen.zig
src/shader/codegen/msl.zig
src/shader/test.zig
src/vulkan.zig

metal: pbr-basic example

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/spirv.zig

AstGen: textureSample builtin

---

src/d3d12.zig
src/metal.zig
src/utils.zig

misc fixes

---

src/d3d12.zig
src/metal.zig
src/shader/codegen/msl.zig

metal: default pipeline layouts

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/shader/test.zig

AstGen: textureStore, textureLoad and workgroupBarrier

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/metal/conv.zig
src/shader/codegen/msl.zig
src/utils.zig
src/vulkan.zig

metal: texture/sampler support

---

src/metal.zig
src/shader/codegen/msl.zig

metal: multiple bind groups

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/utils.zig
src/vulkan.zig

metal: remaining mach-core examples

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig

shader: vector cast

---

src/d3d12.zig
src/d3d12/conv.zig
src/shader/codegen/hlsl.zig

d3d12: pbr-basic example

---

src/d3d12.zig
src/d3d12/conv.zig
src/main.zig
src/metal.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/vulkan.zig

d3d12: remaining mach-core examples

---

src/shader/codegen/msl.zig

metal: implement vector casts

---

src/shader/codegen/spirv.zig

spirv: boids shader

---

src/d3d12.zig
src/metal.zig

{d3d12,metal}: improve reference and state trackers

---

src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/shader/test.zig
src/shader/test/boids-sprite-update.wgsl
src/shader/test/map-async.wgsl

spirv: enable more tests

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig
src/shader/test.zig
src/shader/test/fragmentDeferredRendering.wgsl
src/shader/test/fragmentGBuffersDebugView.wgsl
src/shader/test/fragmentWriteGBuffers.wgsl
src/shader/test/lightUpdate.wgsl
src/shader/test/pbr-basic.wgsl
src/shader/test/vertexTextureQuad.wgsl
src/shader/test/vertexWriteGBuffers.wgsl

spirv: image-blur and pbr-basic

---

src/shader/codegen/spirv.zig
src/shader/test/boids-sprite-update.wgsl
src/shader/test/map-async.wgsl

spirv: arrayLength

---

src/vulkan.zig

vulkan: fix upload recycling

---

src/shader/codegen/spirv.zig
src/vulkan.zig
src/vulkan/conv.zig
src/vulkan/proc.zig

vulkan: render pass layouts, copy barriers, image copies

---

src/shader/codegen/spirv.zig
src/shader/test/gen-texture-light-cube.wgsl
src/shader/test/gen-texture-light.wgsl
src/shader/test/image-blur.wgsl
src/shader/test/procedural-primitives.wgsl

spirv: small fixes

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/spirv.zig
src/shader/test/gen-texture-light-cube.wgsl
src/shader/test/gen-texture-light.wgsl
src/shader/test/pbr-basic.wgsl

shader: flattened inputs

---

src/vulkan.zig
src/vulkan/conv.zig

vulkan: mapAsync and misc fixes

---

build.zig
build.zig.zon
src/d3d12.zig
src/d3d12/workarounds.c
src/main.zig
src/opengl.zig
src/opengl/c.zig

opengl: initial backend

---

src/vulkan.zig
src/vulkan/conv.zig

vulkan: misc-fixes

---

src/d3d12.zig
src/metal.zig
src/opengl.zig
src/opengl/c.zig
src/opengl/proc.zig
src/shader/CodeGen.zig
src/shader/codegen/glsl.zig
src/shader/codegen/hlsl.zig
src/shader/test.zig
src/vulkan.zig

opengl: triangle

---

src/main.zig

expose shader compiler

---

src/d3d12.zig
src/gpu_allocator.zig

implement a gpu allocator for d3d12 backend

---

build.zig
build.zig.zon
src/d3d12.zig
src/metal.zig
src/opengl.zig
src/shader/CodeGen.zig
src/shader/codegen/glsl.zig
src/shader/codegen/msl.zig
src/shader/test.zig
src/vulkan.zig

shader: binding tables and spirv tools

---

src/d3d12.zig
src/gpu_allocator.zig
src/shader/test.zig

fix msl CodeGen tests, gpu_allocator tests, and cleanup of d3d12 mem_allocator

---

src/d3d12.zig
src/main.zig
src/metal.zig
src/opengl.zig
src/shader/Air.zig
src/shader/AstGen.zig
src/shader/CodeGen.zig
src/shader/Tokenizer.zig
src/shader/codegen/glsl.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/msl.zig
src/shader/codegen/spirv.zig
src/shader/test.zig
src/shader/test/builtins.wgsl
src/shader/test/if-else.wgsl
src/shader/test/pbr-basic.wgsl
src/sysgpu/device.zig
src/sysgpu/main.zig
src/sysgpu/shader_module.zig
src/utils.zig
src/vulkan.zig
src/vulkan/conv.zig
src/vulkan/proc.zig

vulkan: some validation error fixes

---

src/shader/Air.zig
src/shader/CodeGen.zig
src/shader/codegen/hlsl.zig
src/shader/codegen/spirv.zig
src/shader/test/procedural-primitives.wgsl

hlsl: add padding to structs where needed

---

src/shader/Air.zig
src/shader/AstGen.zig
src/shader/codegen/spirv.zig

AstGen: order declarations correctly
